### ISSUE TITLE
ainoweb.dev ssl error

### ISSUE THREAD

**Issue by rktjmp** [oestrich/aino#8]
Something misconfigured? 

> Secure Connection Failed
>
> An error occurred during a connection to ainoweb.dev. PR_END_OF_FILE_ERROR

![image](https://user-images.githubusercontent.com/866010/195554212-93467433-55ea-4b68-bb65-2ddaccbee895.png)

**Comment by oestrich** [comment]
Sorry this took so long to get back to. Had some health issues that kept me away from a computer. DigitalOcean updated my k8s cluster and broke my ingress, oops. Guess that's what I get for using k8s! haha

Should be working now, so closing. Thanks for commenting!
